In [1]:
import numpy as np
import tensorflow as tf

In [7]:
a = tf.Variable(tf.truncated_normal(shape=[2,1]))
b = tf.Variable(tf.constant(0.,shape=[2,1]))
init = tf.global_variables_initializer()
op1 = tf.assign(b,a)
op2 = tf.assign(a,[[0.],[0.]])

with tf.Session() as sess:
    sess.run(init)
    print(sess.run(a),sess.run(b))
    sess.run(op1)
    print(sess.run(a),sess.run(b))
    sess.run(op2)
#     sess.run(op1)
    print(sess.run(a),sess.run(b))

[[0.60692424]
 [0.60606205]] [[0.]
 [0.]]
[[0.60692424]
 [0.60606205]] [[0.60692424]
 [0.60606205]]
[[0.]
 [0.]] [[0.60692424]
 [0.60606205]]


In [ ]:
a = np.array((2,3,4)).reshape((1,-1))
a