In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.placeholder(dtype=tf.float32, shape=[None,2], name='states')
b = tf.placeholder(dtype=tf.uint8, shape=[None], name='actions')
c = tf.one_hot(b,depth=3)
d = tf.concat([a,c],1)
p = tf.shape(d)
with tf.Session() as sess:
    feed_dict = {
        'states:0': [[0.,1.],[2.,3.]],
        'actions:0': [1,2]
    }
    output = sess.run(d, feed_dict=feed_dict)
    print(output)

[[0. 1. 0. 1. 0.]
 [2. 3. 0. 0. 1.]]


In [3]:
a = np.array((2,3,4)).reshape((1,-1))
a

array([[2, 3, 4]])